name: Bump stale issues

on:
  push:
    branches: main
  schedule:
    # Run every day at 1am
    - cron: '0 1 * * *'

jobs:
  fresh-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Bump stale issues
        uses: c-hive/fresh-bot@master
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Needs `repo` scope

      - name: Bump stale issues (DEBUG)
        uses: GiovanH/fresh-bot@patch-1
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Needs `repo` scope


